config/routes.rb
Rails.application.routes.draw do

  # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  namespace :admin do
    resources :items, except: [:destroy]
    resources :genres, except: [:new, :show, :destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  namespace :admin do
    get 'homes/top'
    root to: "homes#top"
  end

  namespace :public do
    resources :items, only: [:index, :show]
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post :confirm
        get :thanks
      end
    end
    resources :addresses, except: [:new, :show]
  end
  namespace :public do
    get 'homes/top'
    get 'homes/about'
   end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer


def subtotal
    item.with_tax_price * amount
end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses,dependent: :destroy

  def active_for_authentication?
    super && (is_active == true)
  end



end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  has_one_attached :image
  validates :image, presence: true

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  def total_payment

  end

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting:0, confirmation:1, making:2, packing:3, sended:4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item


def subtotal
    item.with_tax_price * amount
end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all

  end

  def show
    @customer = Customer.find(params[:id])

  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private

  def customer_params
   params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path(genre.id)
  end



  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
    redirect_to admin_items_path
    else
    render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email])
  # end

# def after_sign_in_path_for(resource)
#   case resource
#   when Admin
#     admin_root_path
#   when Customer
#   root_path
#   end
# end


# def after_sign_out_path_for(resource)
#   case resource
#   when Admin
#     new_admin_session_path
#   when Customer
#   public_items_index_path
#   end

# end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_details_helper.rb
module Admin::OrdersDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class= "row" >
  <div class= "container">

<h2>会員情報編集</h2>


<%= form_with model: @customer, url: admin_customer_path do |f| %>

  <h4>氏名</h4>
  <%= f.text_field :last_name %>
  <%= f.text_field :first_name %>
  <h4>フリガナ</h4>
  <%= f.text_field :last_name_kana %>
  <%= f.text_field :first_name_kana %>
  <h4>郵便番号</h4>
  <%= f.text_field :postal_code %>
  <h4>住所</h4>
  <%= f.text_field :address %>
  <h4>電話番号</h4>
  <%= f.text_field :telephone_number %>
  <h4>メールアドレス</h4>
  <%= f.text_field :email %>
  <h4>会員ステータス</h4>
  <%= f.radio_button :is_active, :true %>
  <%= f.label :is_active, "有効", {value: :true, style: "display: inline-block;"} %>
  <%= f.radio_button :is_active, :false %>
  <%= f.label :is_active, "退会", {value: :false, style: "display: inline-block;"} %>


  <%= f.submit '編集内容を保存' %>

  <% end %>

</div>
</div>

app/views/admin/customers/index.html.erb
<div class= "row" >
  <div class= "container">

<h2>会員一覧</h2>
<table class= "table">
  <thead>
    <tr>
      <th></th>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td></td>
        <td><%= customer.id %></td>
        <td>
          <%= link_to admin_customer_path(customer) do %>
            <span><%= customer.last_name %><%= customer.first_name %></span>
          <% end %>
        </td>
        <td>
          <span><%= customer.email %></span>
        </td>
        <td>
          <% if customer.is_active == true %> <p>有効</p>
          <% else %> <p>退会</p>
          <% end %>
        </td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>

app/views/admin/customers/show.html.erb
<div class= "row" >
  <div class= "container">
    <ul class="list-group">

<h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>

<ul class="list-group list-group-horizontal">
  <li class="list-group-item">会員ID</li>
  <li class="list-group-item"><%= @customer.id %></li>
</ul>
<ul class="list-group list-group-horizontal">
  <li class="list-group-item">氏名</li>
  <li class="list-group-item"><%= @customer.last_name %><%= @customer.first_name %></li>
</ul>
<ul class="list-group list-group-horizontal">
  <li class="list-group-item">フリガナ</li>
  <li class="list-group-item"><%= @customer.last_name_kana %><%= @customer.first_name_kana %></li>
</ul>
<ul class="list-group list-group-horizontal">
  <li class="list-group-item">郵便番号</li>
  <li class="list-group-item"><%= @customer.postal_code %></li>
</ul>
<ul class="list-group list-group-horizontal">
  <li class="list-group-item">住所</li>
  <li class="list-group-item"><%= @customer.address %></li>
</ul>
<ul class="list-group list-group-horizontal">
  <li class="list-group-item">電話番号</li>
  <li class="list-group-item"><%= @customer.telephone_number %></li>
</ul>
<ul class="list-group list-group-horizontal">
  <li class="list-group-item">メールアドレス</li>
  <li class="list-group-item"><%= @customer.email %></li>
</ul>
<ul class="list-group list-group-horizontal">
  <li class="list-group-item">会員ステータス</li>
  <li class="list-group-item"><% if @customer.is_active == true %> <p>有効</p>
                                <% else %> <p>退会</p>
                              <% end %></li>
</ul>


  </thead>

</div>
</div>

  <button type="button" class="btn btn-outline-primary"><%= link_to "編集する", edit_admin_customer_path %></button>
  <button type="button" class="btn btn-outline-primary"><%= link_to "注文履歴一覧を見る",admin_homes_top_path %></button>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>

app/views/publics/customers/edit.html.erb
<h1>Public::Customers#edit</h1>
<p>Find me in app/views/public/customers/edit.html.erb</p>

app/views/publics/customers/show.html.erb
<h1>Public::Customers#show</h1>
<p>Find me in app/views/public/customers/show.html.erb</p>

app/views/publics/customers/unsubscribe.html.erb
<h1>Public::Customers#unsubscribe</h1>
<p>Find me in app/views/public/customers/unsubscribe.html.erb</p>

app/views/publics/customers/update.html.erb
<h1>Public::Customers#update</h1>
<p>Find me in app/views/public/customers/update.html.erb</p>

app/views/publics/customers/withdraw.html.erb
<h1>Public::Customers#withdraw</h1>
<p>Find me in app/views/public/customers/withdraw.html.erb</p>