config/routes.rb
Rails.application.routes.draw do

  # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  namespace :admin do
    resources :items, except: [:destroy]
    resources :genres, except: [:new, :show, :destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  namespace :admin do
    get 'homes/top'
    root to: "homes#top"
  end

  namespace :public do
    resources :items, only: [:index, :show]
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post :confirm
        get :thanks
      end
    end
    resources :addresses, except: [:new, :show]
  end
  namespace :public do
    get 'homes/top'
    get 'homes/about'
   end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer


def subtotal
    item.with_tax_price * amount
end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses,dependent: :destroy

  def active_for_authentication?
    super && (is_active == true)
  end



end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  has_one_attached :image
  validates :image, presence: true

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  def total_payment

  end

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting:0, confirmation:1, making:2, packing:3, sended:4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item


def subtotal
    item.with_tax_price * amount
end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path(genre.id)
  end



  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
    redirect_to admin_items_path
    else
    render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController

  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email])
  # end

# def after_sign_in_path_for(resource)
#   case resource
#   when Admin
#     admin_root_path
#   when Customer
#   root_path
#   end
# end


# def after_sign_out_path_for(resource)
#   case resource
#   when Admin
#     new_admin_session_path
#   when Customer
#   public_items_index_path
#   end

# end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_details_helper.rb
module Admin::OrdersDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class= "row" >
  <div class= "container"><h2>ジャンル編集</h2>


<%= form_with model: @genre, url: admin_genre_path(@genre.id) do |f| %>

  <h4>ジャンル名</h4>
  <%= f.text_field :name %>

  <%= f.submit '変更を保存' %>

<% end %>


</div>
</div>

app/views/admin/genres/index.html.erb
<h2>ジャンル一覧・追加</h2>

<%= form_with model: @genre, url: admin_genres_path do |f| %>
<h4>ジャンル名</h4>
<%= f.text_field :name %>

<%= f.submit '新規登録' %>
<% end %>


<h4>ジャンル</h4>

<% @genres.each do |genre| %>
<ul>
  <li><span><%= genre.name %></span>
  <%= link_to "編集する", edit_admin_genre_path(genre) %>
  </li>
</ul>
<% end %>

app/views/admin/orders/show.html.erb
<h2>注文履歴詳細</h2>

<table class= "table">
  <thead>
      <th>購入者</th>
      <th>注文日</th>
      <th>配送先</th>
      <th>支払い方法</th>
      <th>注文ステータス</th>
  </thead>
  <tbody>
    　<th><%= @order.customer.last_name + @order.customer.first_name %></th>
    　<th><%= @order.created_at %></th>
    　<th><%= @order.address %></th>
    　<th><%= @order.payment_method_i18n %></th>
    　<th><%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
            <%= f.select :order_status, Order.order_statuses.keys, class: "order_status" %>
            <%= f.submit "更新" , class: "btn btn-outline-success" %>
            <% end %></th>
　 </tbody>
　</table>
　<table>
　 <thead>
　  <th>商品名</th>
　  <th>単価（税込）</th>
　  <th>数量</th>
　  <th>小計</th>
　 </thead>
　 <tbody>
　  <% @total = 0 %>
　  <% @order_details.each do |order_detail| %>
　  <tr>
　   <td><%= order_detail.item.name %></td>
　   <td><%= order_detail.item.with_tax_price %></td>
　   <td><%= order_detail.amount %></td>
　   <td><%= order_detail.subtotal %></td>
　  </tr>
    <% @total = @total + order_detail.subtotal %>
　  <% end %>
　 </tbody>

　</table>

 <ul class="list-group list-group-horizontal">
  <li class="list-group-item">商品合計</li>
  <li class="list-group-item"><%= @total %>円</li>
 </ul>
 <ul class="list-group list-group-horizontal">
  <li class="list-group-item">送料</li>
  <li class="list-group-item">800円</li>
 </ul><ul class="list-group list-group-horizontal">
  <li class="list-group-item">請求金額合計</li>
  <li class="list-group-item"><%= @total + 800 %>円</li>
 </ul>
</div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>

app/views/publics/items/index.html.erb
<h1>Public::Items#index</h1>
<p>Find me in app/views/public/items/index.html.erb</p>

app/views/publics/items/show.html.erb
<h1>Public::Items#show</h1>
<p>Find me in app/views/public/items/show.html.erb</p>